<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CampaignsTriggerSendPostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        return $type === 'Braze\\Model\\CampaignsTriggerSendPostBody';
    }

    public function supportsNormalization($data, $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === 'Braze\\Model\\CampaignsTriggerSendPostBody';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\CampaignsTriggerSendPostBody();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('campaign_id', $data)) {
            $object->setCampaignId($data['campaign_id']);
            unset($data['campaign_id']);
        }
        if (\array_key_exists('send_id', $data)) {
            $object->setSendId($data['send_id']);
            unset($data['send_id']);
        }
        if (\array_key_exists('trigger_properties', $data)) {
            $object->setTriggerProperties($data['trigger_properties']);
            unset($data['trigger_properties']);
        }
        if (\array_key_exists('broadcast', $data)) {
            $object->setBroadcast($data['broadcast']);
            unset($data['broadcast']);
        }
        if (\array_key_exists('audience', $data)) {
            $object->setAudience($this->denormalizer->denormalize($data['audience'], 'Braze\\Model\\CampaignsTriggerSendPostBodyAudience', 'json', $context));
            unset($data['audience']);
        }
        if (\array_key_exists('recipients', $data)) {
            $values = [];
            foreach ($data['recipients'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, 'Braze\\Model\\CampaignsTriggerSendPostBodyRecipientsItem', 'json', $context);
            }
            $object->setRecipients($values);
            unset($data['recipients']);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_1;
            }
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if ($object->isInitialized('campaignId') && null !== $object->getCampaignId()) {
            $data['campaign_id'] = $object->getCampaignId();
        }
        if ($object->isInitialized('sendId') && null !== $object->getSendId()) {
            $data['send_id'] = $object->getSendId();
        }
        if ($object->isInitialized('triggerProperties') && null !== $object->getTriggerProperties()) {
            $data['trigger_properties'] = $object->getTriggerProperties();
        }
        if ($object->isInitialized('broadcast') && null !== $object->getBroadcast()) {
            $data['broadcast'] = $object->getBroadcast();
        }
        if ($object->isInitialized('audience') && null !== $object->getAudience()) {
            $data['audience'] = $this->normalizer->normalize($object->getAudience(), 'json', $context);
        }
        if ($object->isInitialized('recipients') && null !== $object->getRecipients()) {
            $values = [];
            foreach ($object->getRecipients() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data['recipients'] = $values;
        }
        foreach ($object as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $data[$key] = $value_1;
            }
        }

        return $data;
    }

    public function getSupportedTypes(string $format = null): array
    {
        return ['Braze\\Model\\CampaignsTriggerSendPostBody' => false];
    }
}
