<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CanvasTriggerSendPostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\CanvasTriggerSendPostBody::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\CanvasTriggerSendPostBody::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\CanvasTriggerSendPostBody();
        if (\array_key_exists('broadcast', $data) && \is_int($data['broadcast'])) {
            $data['broadcast'] = (bool) $data['broadcast'];
        }
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('canvas_id', $data)) {
            $object->setCanvasId($data['canvas_id']);
            unset($data['canvas_id']);
        }
        if (\array_key_exists('canvas_entry_properties', $data)) {
            $object->setCanvasEntryProperties($this->denormalizer->denormalize($data['canvas_entry_properties'], \Braze\Model\CanvasTriggerSendPostBodyCanvasEntryProperties::class, 'json', $context));
            unset($data['canvas_entry_properties']);
        }
        if (\array_key_exists('broadcast', $data)) {
            $object->setBroadcast($data['broadcast']);
            unset($data['broadcast']);
        }
        if (\array_key_exists('audience', $data)) {
            $object->setAudience($this->denormalizer->denormalize($data['audience'], \Braze\Model\CanvasTriggerSendPostBodyAudience::class, 'json', $context));
            unset($data['audience']);
        }
        if (\array_key_exists('recipients', $data)) {
            $values = [];
            foreach ($data['recipients'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, \Braze\Model\CanvasTriggerSendPostBodyRecipientsItem::class, 'json', $context);
            }
            $object->setRecipients($values);
            unset($data['recipients']);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('canvasId') && null !== $data->getCanvasId()) {
            $dataArray['canvas_id'] = $data->getCanvasId();
        }
        if ($data->isInitialized('canvasEntryProperties') && null !== $data->getCanvasEntryProperties()) {
            $dataArray['canvas_entry_properties'] = $this->normalizer->normalize($data->getCanvasEntryProperties(), 'json', $context);
        }
        if ($data->isInitialized('broadcast') && null !== $data->getBroadcast()) {
            $dataArray['broadcast'] = $data->getBroadcast();
        }
        if ($data->isInitialized('audience') && null !== $data->getAudience()) {
            $dataArray['audience'] = $this->normalizer->normalize($data->getAudience(), 'json', $context);
        }
        if ($data->isInitialized('recipients') && null !== $data->getRecipients()) {
            $values = [];
            foreach ($data->getRecipients() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $dataArray['recipients'] = $values;
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Braze\Model\CanvasTriggerSendPostBody::class => false];
    }
}
