<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class CanvasTriggerScheduleCreatePostBodyRecipientsItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\CanvasTriggerScheduleCreatePostBodyRecipientsItem::class;
    }

    public function supportsNormalization(mixed $data, string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\CanvasTriggerScheduleCreatePostBodyRecipientsItem::class;
    }

    public function denormalize(mixed $data, string $type, string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\CanvasTriggerScheduleCreatePostBodyRecipientsItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('user_alias', $data)) {
            $object->setUserAlias($data['user_alias']);
            unset($data['user_alias']);
        }
        if (\array_key_exists('external_user_id', $data)) {
            $object->setExternalUserId($data['external_user_id']);
            unset($data['external_user_id']);
        }
        if (\array_key_exists('trigger_properties', $data)) {
            $values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['trigger_properties'] as $key => $value) {
                $values[$key] = $value;
            }
            $object->setTriggerProperties($values);
            unset($data['trigger_properties']);
        }
        if (\array_key_exists('canvas_entry_properties', $data)) {
            $values_1 = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
            foreach ($data['canvas_entry_properties'] as $key_1 => $value_1) {
                $values_1[$key_1] = $value_1;
            }
            $object->setCanvasEntryProperties($values_1);
            unset($data['canvas_entry_properties']);
        }
        foreach ($data as $key_2 => $value_2) {
            if (preg_match('/.*/', (string) $key_2)) {
                $object[$key_2] = $value_2;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('userAlias') && null !== $data->getUserAlias()) {
            $dataArray['user_alias'] = $data->getUserAlias();
        }
        if ($data->isInitialized('externalUserId') && null !== $data->getExternalUserId()) {
            $dataArray['external_user_id'] = $data->getExternalUserId();
        }
        if ($data->isInitialized('triggerProperties') && null !== $data->getTriggerProperties()) {
            $values = [];
            foreach ($data->getTriggerProperties() as $key => $value) {
                $values[$key] = $value;
            }
            $dataArray['trigger_properties'] = $values;
        }
        if ($data->isInitialized('canvasEntryProperties') && null !== $data->getCanvasEntryProperties()) {
            $values_1 = [];
            foreach ($data->getCanvasEntryProperties() as $key_1 => $value_1) {
                $values_1[$key_1] = $value_1;
            }
            $dataArray['canvas_entry_properties'] = $values_1;
        }
        foreach ($data as $key_2 => $value_2) {
            if (preg_match('/.*/', (string) $key_2)) {
                $dataArray[$key_2] = $value_2;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(string $format = null): array
    {
        return [\Braze\Model\CanvasTriggerScheduleCreatePostBodyRecipientsItem::class => false];
    }
}
