<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class MessagesScheduleUpdatePostBodyMessagesNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\MessagesScheduleUpdatePostBodyMessages::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\MessagesScheduleUpdatePostBodyMessages::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\MessagesScheduleUpdatePostBodyMessages();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('apple_push', $data)) {
            $object->setApplePush($this->denormalizer->denormalize($data['apple_push'], \Braze\Model\MessagesScheduleUpdatePostBodyMessagesApplePush::class, 'json', $context));
            unset($data['apple_push']);
        }
        if (\array_key_exists('android_push', $data)) {
            $object->setAndroidPush($this->denormalizer->denormalize($data['android_push'], \Braze\Model\MessagesScheduleUpdatePostBodyMessagesAndroidPush::class, 'json', $context));
            unset($data['android_push']);
        }
        if (\array_key_exists('sms', $data)) {
            $object->setSms($this->denormalizer->denormalize($data['sms'], \Braze\Model\MessagesScheduleUpdatePostBodyMessagesSms::class, 'json', $context));
            unset($data['sms']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('applePush') && null !== $data->getApplePush()) {
            $dataArray['apple_push'] = $this->normalizer->normalize($data->getApplePush(), 'json', $context);
        }
        if ($data->isInitialized('androidPush') && null !== $data->getAndroidPush()) {
            $dataArray['android_push'] = $this->normalizer->normalize($data->getAndroidPush(), 'json', $context);
        }
        if ($data->isInitialized('sms') && null !== $data->getSms()) {
            $dataArray['sms'] = $this->normalizer->normalize($data->getSms(), 'json', $context);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Braze\Model\MessagesScheduleUpdatePostBodyMessages::class => false];
    }
}
