<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class MessagesScheduleUpdatePostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Braze\Model\MessagesScheduleUpdatePostBody::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === Braze\Model\MessagesScheduleUpdatePostBody::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Braze\Model\MessagesScheduleUpdatePostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('schedule_id', $data)) {
                $object->setScheduleId($data['schedule_id']);
                unset($data['schedule_id']);
            }
            if (\array_key_exists('schedule', $data)) {
                $object->setSchedule($this->denormalizer->denormalize($data['schedule'], \Braze\Model\MessagesScheduleUpdatePostBodySchedule::class, 'json', $context));
                unset($data['schedule']);
            }
            if (\array_key_exists('messages', $data)) {
                $object->setMessages($this->denormalizer->denormalize($data['messages'], \Braze\Model\MessagesScheduleUpdatePostBodyMessages::class, 'json', $context));
                unset($data['messages']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('scheduleId') && null !== $object->getScheduleId()) {
                $data['schedule_id'] = $object->getScheduleId();
            }
            if ($object->isInitialized('schedule') && null !== $object->getSchedule()) {
                $data['schedule'] = $this->normalizer->normalize($object->getSchedule(), 'json', $context);
            }
            if ($object->isInitialized('messages') && null !== $object->getMessages()) {
                $data['messages'] = $this->normalizer->normalize($object->getMessages(), 'json', $context);
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Braze\Model\MessagesScheduleUpdatePostBody::class => false];
        }
    }
} else {
    class MessagesScheduleUpdatePostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \Braze\Model\MessagesScheduleUpdatePostBody::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === Braze\Model\MessagesScheduleUpdatePostBody::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Braze\Model\MessagesScheduleUpdatePostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('schedule_id', $data)) {
                $object->setScheduleId($data['schedule_id']);
                unset($data['schedule_id']);
            }
            if (\array_key_exists('schedule', $data)) {
                $object->setSchedule($this->denormalizer->denormalize($data['schedule'], \Braze\Model\MessagesScheduleUpdatePostBodySchedule::class, 'json', $context));
                unset($data['schedule']);
            }
            if (\array_key_exists('messages', $data)) {
                $object->setMessages($this->denormalizer->denormalize($data['messages'], \Braze\Model\MessagesScheduleUpdatePostBodyMessages::class, 'json', $context));
                unset($data['messages']);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('scheduleId') && null !== $object->getScheduleId()) {
                $data['schedule_id'] = $object->getScheduleId();
            }
            if ($object->isInitialized('schedule') && null !== $object->getSchedule()) {
                $data['schedule'] = $this->normalizer->normalize($object->getSchedule(), 'json', $context);
            }
            if ($object->isInitialized('messages') && null !== $object->getMessages()) {
                $data['messages'] = $this->normalizer->normalize($object->getMessages(), 'json', $context);
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\Braze\Model\MessagesScheduleUpdatePostBody::class => false];
        }
    }
}
