<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ScimV2UsersPostBodyPermissionsAppGroupItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItem::class;
    }

    public function supportsNormalization(mixed $data, string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItem::class;
    }

    public function denormalize(mixed $data, string $type, string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('appGroupName', $data)) {
            $object->setAppGroupName($data['appGroupName']);
            unset($data['appGroupName']);
        }
        if (\array_key_exists('appGroupPermissions', $data)) {
            $values = [];
            foreach ($data['appGroupPermissions'] as $value) {
                $values[] = $value;
            }
            $object->setAppGroupPermissions($values);
            unset($data['appGroupPermissions']);
        }
        if (\array_key_exists('team', $data)) {
            $values_1 = [];
            foreach ($data['team'] as $value_1) {
                $values_1[] = $this->denormalizer->denormalize($value_1, \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItemTeamItem::class, 'json', $context);
            }
            $object->setTeam($values_1);
            unset($data['team']);
        }
        foreach ($data as $key => $value_2) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_2;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('appGroupName') && null !== $data->getAppGroupName()) {
            $dataArray['appGroupName'] = $data->getAppGroupName();
        }
        if ($data->isInitialized('appGroupPermissions') && null !== $data->getAppGroupPermissions()) {
            $values = [];
            foreach ($data->getAppGroupPermissions() as $value) {
                $values[] = $value;
            }
            $dataArray['appGroupPermissions'] = $values;
        }
        if ($data->isInitialized('team') && null !== $data->getTeam()) {
            $values_1 = [];
            foreach ($data->getTeam() as $value_1) {
                $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
            }
            $dataArray['team'] = $values_1;
        }
        foreach ($data as $key => $value_2) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_2;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(string $format = null): array
    {
        return [\Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItem::class => false];
    }
}
