<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ScimV2UsersPostBodyPermissionsAppGroupItemTeamItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItemTeamItem::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItemTeamItem::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItemTeamItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('teamName', $data)) {
            $object->setTeamName($data['teamName']);
            unset($data['teamName']);
        }
        if (\array_key_exists('teamPermissions', $data)) {
            $values = [];
            foreach ($data['teamPermissions'] as $value) {
                $values[] = $value;
            }
            $object->setTeamPermissions($values);
            unset($data['teamPermissions']);
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_1;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('teamName') && null !== $data->getTeamName()) {
            $dataArray['teamName'] = $data->getTeamName();
        }
        if ($data->isInitialized('teamPermissions') && null !== $data->getTeamPermissions()) {
            $values = [];
            foreach ($data->getTeamPermissions() as $value) {
                $values[] = $value;
            }
            $dataArray['teamPermissions'] = $values;
        }
        foreach ($data as $key => $value_1) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_1;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Braze\Model\ScimV2UsersPostBodyPermissionsAppGroupItemTeamItem::class => false];
    }
}
