<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class UsersDeletePostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, string $format = null, array $context = []): bool
        {
            return $type === 'Braze\\Model\\UsersDeletePostBody';
        }

        public function supportsNormalization(mixed $data, string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Braze\\Model\\UsersDeletePostBody';
        }

        public function denormalize(mixed $data, string $type, string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Braze\Model\UsersDeletePostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('external_ids', $data)) {
                $values = [];
                foreach ($data['external_ids'] as $value) {
                    $values[] = $value;
                }
                $object->setExternalIds($values);
                unset($data['external_ids']);
            }
            if (\array_key_exists('braze_ids', $data)) {
                $values_1 = [];
                foreach ($data['braze_ids'] as $value_1) {
                    $values_1[] = $value_1;
                }
                $object->setBrazeIds($values_1);
                unset($data['braze_ids']);
            }
            if (\array_key_exists('user_aliases', $data)) {
                $values_2 = [];
                foreach ($data['user_aliases'] as $value_2) {
                    $values_2[] = $this->denormalizer->denormalize($value_2, 'Braze\\Model\\UsersDeletePostBodyUserAliasesItem', 'json', $context);
                }
                $object->setUserAliases($values_2);
                unset($data['user_aliases']);
            }
            foreach ($data as $key => $value_3) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_3;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            if ($object->isInitialized('externalIds') && null !== $object->getExternalIds()) {
                $values = [];
                foreach ($object->getExternalIds() as $value) {
                    $values[] = $value;
                }
                $data['external_ids'] = $values;
            }
            if ($object->isInitialized('brazeIds') && null !== $object->getBrazeIds()) {
                $values_1 = [];
                foreach ($object->getBrazeIds() as $value_1) {
                    $values_1[] = $value_1;
                }
                $data['braze_ids'] = $values_1;
            }
            if ($object->isInitialized('userAliases') && null !== $object->getUserAliases()) {
                $values_2 = [];
                foreach ($object->getUserAliases() as $value_2) {
                    $values_2[] = $this->normalizer->normalize($value_2, 'json', $context);
                }
                $data['user_aliases'] = $values_2;
            }
            foreach ($object as $key => $value_3) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_3;
                }
            }

            return $data;
        }

        public function getSupportedTypes(string $format = null): array
        {
            return ['Braze\\Model\\UsersDeletePostBody' => false];
        }
    }
} else {
    class UsersDeletePostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, string $format = null, array $context = []): bool
        {
            return $type === 'Braze\\Model\\UsersDeletePostBody';
        }

        public function supportsNormalization(mixed $data, string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === 'Braze\\Model\\UsersDeletePostBody';
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \Braze\Model\UsersDeletePostBody();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('external_ids', $data)) {
                $values = [];
                foreach ($data['external_ids'] as $value) {
                    $values[] = $value;
                }
                $object->setExternalIds($values);
                unset($data['external_ids']);
            }
            if (\array_key_exists('braze_ids', $data)) {
                $values_1 = [];
                foreach ($data['braze_ids'] as $value_1) {
                    $values_1[] = $value_1;
                }
                $object->setBrazeIds($values_1);
                unset($data['braze_ids']);
            }
            if (\array_key_exists('user_aliases', $data)) {
                $values_2 = [];
                foreach ($data['user_aliases'] as $value_2) {
                    $values_2[] = $this->denormalizer->denormalize($value_2, 'Braze\\Model\\UsersDeletePostBodyUserAliasesItem', 'json', $context);
                }
                $object->setUserAliases($values_2);
                unset($data['user_aliases']);
            }
            foreach ($data as $key => $value_3) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value_3;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            if ($object->isInitialized('externalIds') && null !== $object->getExternalIds()) {
                $values = [];
                foreach ($object->getExternalIds() as $value) {
                    $values[] = $value;
                }
                $data['external_ids'] = $values;
            }
            if ($object->isInitialized('brazeIds') && null !== $object->getBrazeIds()) {
                $values_1 = [];
                foreach ($object->getBrazeIds() as $value_1) {
                    $values_1[] = $value_1;
                }
                $data['braze_ids'] = $values_1;
            }
            if ($object->isInitialized('userAliases') && null !== $object->getUserAliases()) {
                $values_2 = [];
                foreach ($object->getUserAliases() as $value_2) {
                    $values_2[] = $this->normalizer->normalize($value_2, 'json', $context);
                }
                $data['user_aliases'] = $values_2;
            }
            foreach ($object as $key => $value_3) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value_3;
                }
            }

            return $data;
        }

        public function getSupportedTypes(string $format = null): array
        {
            return ['Braze\\Model\\UsersDeletePostBody' => false];
        }
    }
}
