<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class UsersIdentifyPostBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\UsersIdentifyPostBody::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\UsersIdentifyPostBody::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\UsersIdentifyPostBody();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('aliases_to_identify', $data)) {
            $values = [];
            foreach ($data['aliases_to_identify'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, \Braze\Model\UsersIdentifyPostBodyAliasesToIdentifyItem::class, 'json', $context);
            }
            $object->setAliasesToIdentify($values);
            unset($data['aliases_to_identify']);
        }
        if (\array_key_exists('emails_to_identify', $data)) {
            $values_1 = [];
            foreach ($data['emails_to_identify'] as $value_1) {
                $values_1[] = $this->denormalizer->denormalize($value_1, \Braze\Model\UsersIdentifyPostBodyEmailsToIdentifyItem::class, 'json', $context);
            }
            $object->setEmailsToIdentify($values_1);
            unset($data['emails_to_identify']);
        }
        if (\array_key_exists('phone_numbers_to_identify', $data)) {
            $values_2 = [];
            foreach ($data['phone_numbers_to_identify'] as $value_2) {
                $values_2[] = $this->denormalizer->denormalize($value_2, \Braze\Model\UsersIdentifyPostBodyPhoneNumbersToIdentifyItem::class, 'json', $context);
            }
            $object->setPhoneNumbersToIdentify($values_2);
            unset($data['phone_numbers_to_identify']);
        }
        if (\array_key_exists('merge_behavior', $data)) {
            $object->setMergeBehavior($data['merge_behavior']);
            unset($data['merge_behavior']);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_3;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('aliasesToIdentify') && null !== $data->getAliasesToIdentify()) {
            $values = [];
            foreach ($data->getAliasesToIdentify() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $dataArray['aliases_to_identify'] = $values;
        }
        if ($data->isInitialized('emailsToIdentify') && null !== $data->getEmailsToIdentify()) {
            $values_1 = [];
            foreach ($data->getEmailsToIdentify() as $value_1) {
                $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
            }
            $dataArray['emails_to_identify'] = $values_1;
        }
        if ($data->isInitialized('phoneNumbersToIdentify') && null !== $data->getPhoneNumbersToIdentify()) {
            $values_2 = [];
            foreach ($data->getPhoneNumbersToIdentify() as $value_2) {
                $values_2[] = $this->normalizer->normalize($value_2, 'json', $context);
            }
            $dataArray['phone_numbers_to_identify'] = $values_2;
        }
        if ($data->isInitialized('mergeBehavior') && null !== $data->getMergeBehavior()) {
            $dataArray['merge_behavior'] = $data->getMergeBehavior();
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_3;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Braze\Model\UsersIdentifyPostBody::class => false];
    }
}
