<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Normalizer;

use Braze\Runtime\Normalizer\CheckArray;
use Braze\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class V2SubscriptionStatusSetPostBodySubscriptionGroupsItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
    {
        return $type === \Braze\Model\V2SubscriptionStatusSetPostBodySubscriptionGroupsItem::class;
    }

    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === \Braze\Model\V2SubscriptionStatusSetPostBodySubscriptionGroupsItem::class;
    }

    public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Braze\Model\V2SubscriptionStatusSetPostBodySubscriptionGroupsItem();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('subscription_group_id', $data)) {
            $object->setSubscriptionGroupId($data['subscription_group_id']);
            unset($data['subscription_group_id']);
        }
        if (\array_key_exists('subscription_state', $data)) {
            $object->setSubscriptionState($data['subscription_state']);
            unset($data['subscription_state']);
        }
        if (\array_key_exists('external_ids', $data)) {
            $values = [];
            foreach ($data['external_ids'] as $value) {
                $values[] = $value;
            }
            $object->setExternalIds($values);
            unset($data['external_ids']);
        }
        if (\array_key_exists('emails', $data)) {
            $values_1 = [];
            foreach ($data['emails'] as $value_1) {
                $values_1[] = $value_1;
            }
            $object->setEmails($values_1);
            unset($data['emails']);
        }
        if (\array_key_exists('phones', $data)) {
            $values_2 = [];
            foreach ($data['phones'] as $value_2) {
                $values_2[] = $value_2;
            }
            $object->setPhones($values_2);
            unset($data['phones']);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_3;
            }
        }

        return $object;
    }

    public function normalize(mixed $data, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        $dataArray = [];
        if ($data->isInitialized('subscriptionGroupId') && null !== $data->getSubscriptionGroupId()) {
            $dataArray['subscription_group_id'] = $data->getSubscriptionGroupId();
        }
        if ($data->isInitialized('subscriptionState') && null !== $data->getSubscriptionState()) {
            $dataArray['subscription_state'] = $data->getSubscriptionState();
        }
        if ($data->isInitialized('externalIds') && null !== $data->getExternalIds()) {
            $values = [];
            foreach ($data->getExternalIds() as $value) {
                $values[] = $value;
            }
            $dataArray['external_ids'] = $values;
        }
        if ($data->isInitialized('emails') && null !== $data->getEmails()) {
            $values_1 = [];
            foreach ($data->getEmails() as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['emails'] = $values_1;
        }
        if ($data->isInitialized('phones') && null !== $data->getPhones()) {
            $values_2 = [];
            foreach ($data->getPhones() as $value_2) {
                $values_2[] = $value_2;
            }
            $dataArray['phones'] = $values_2;
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $dataArray[$key] = $value_3;
            }
        }

        return $dataArray;
    }

    public function getSupportedTypes(?string $format = null): array
    {
        return [\Braze\Model\V2SubscriptionStatusSetPostBodySubscriptionGroupsItem::class => false];
    }
}
