<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Endpoint;

class PostContentBlocksCreate extends \Braze\Runtime\Client\BaseEndpoint implements \Braze\Runtime\Client\Endpoint
{
    use \Braze\Runtime\Client\EndpointTrait;

    /**
     * > Use this endpoint to create a [Content Block](https://www.braze.com/docs/user_guide/engagement_tools/templates_and_media/content_blocks/).
     *
     * ## Prerequisites
     *
     * To use this endpoint, you’ll need an [API key](https://www.braze.com/docs/api/api_key/) with the `content_blocks.create` permission.
     *
     * ## Rate limit
     *
     * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
     *
     * ## Request parameters
     *
     * | Parameter | Required | Data Type | Description |
     * | --- | --- | --- | --- |
     * | `name` | Required | String | Name of the Content Block. Must be less than 100 characters. |
     * | `description` | Optional | String | Description of the Content Block. Must be less than 250 characters. |
     * | `content` | Required | String | HTML or text content within the Content Block. |
     * | `state` | Optional | String | Choose `active` or `draft`. Defaults to `active` if not specified. |
     * | `tags` | Optional | Array of strings | [Tags](https://www.braze.com/docs/user_guide/administrative/app_settings/manage_app_group/tags/) must already exist. |
     *
     * ## Example request
     *
     * ``` json
     * Copiedcurl --location --request POST 'https://rest.iad-01.braze.com/content_blocks/create' \
     * --header 'Content-Type: application/json' \
     * --header 'Authorization: Bearer YOUR_REST_API_KEY' \
     * --data-raw '{
     *   "name": "content_block",
     *   "description": "This is my Content Block",
     *   "content": "HTML content within block",
     *   "state": "draft",
     *   "tags": ["marketing"]
     * }'
     *
     *  ```
     *
     * ## Response
     *
     * ``` json
     * Content-Type: application/json
     * Authorization: Bearer YOUR_REST_API_KEY
     * {
     *   "content_block_id": (string) Your newly generated block id,
     *   "liquid_tag": (string) The generated block tag from the Content Block name,
     *   "created_at": (string) The time the Content Block was created in ISO 8601,
     *   "message": "success"
     * }
     *
     *  ```
     *
     * ## Troubleshooting
     *
     * The following table lists possible returned errors and their associated troubleshooting steps.
     *
     * | Error | Troubleshooting |
     * | --- | --- |
     * | `Content cannot be blank` |  |
     * | `Content must be a string` | Make sure your content is encapsulated in quotes (`""`). |
     * | `Content must be smaller than 50kb` | The content in your Content Block must be less than 50kb total. |
     * | `Content contains malformed liquid` | The Liquid provided is not valid or parsable. Try again with valid Liquid or reach out to support. |
     * | `Content Block cannot be referenced within itself` |  |
     * | `Content Block description cannot be blank` |  |
     * | `Content Block description must be a string` | Make sure your Content Block description is encapsulated in quotes (`""`). |
     * | `Content Block description must be shorter than 250 characters` |  |
     * | `Content Block name cannot be blank` |  |
     * | `Content Block name must be shorter than 100 characters` |  |
     * | `Content Block name can only contain alphanumeric characters` | Content Block names can include any of the following characters: the letters (capitalized or lowercase) `A` through `Z`, the numbers `0` through `9`, dashes `-`, and underscores `_`. It cannot contain non-alphanumeric characters like emojis, `!`, `@`, `~`, `&`, and other “special” characters. |
     * | `Content Block with this name already exists` | Try a different name. |
     * | `Content Block state must be either active or draft` |  |
     * | `Tags must be an array` | Tags must be formatted as an array of strings, for example `["marketing", "promotional", "transactional"]`. |
     * | `All tags must be strings` | Make sure your tags are encapsulated in quotes (`""`). |
     * | `Some tags could not be found` | To add a tag when creating a Content Block, the tag must already exist in Braze. |
     *
     * @param array $headerParameters {
     *
     * @var string $Content-Type
     * @var string $Authorization
     *             }
     */
    public function __construct(?\Braze\Model\ContentBlocksCreatePostBody $requestBody = null, array $headerParameters = [])
    {
        $this->body = $requestBody;
        $this->headerParameters = $headerParameters;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return '/content_blocks/create';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \Braze\Model\ContentBlocksCreatePostBody) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getHeadersOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getHeadersOptionsResolver();
        $optionsResolver->setDefined(['Content-Type', 'Authorization']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults([]);
        $optionsResolver->addAllowedTypes('Content-Type', ['string']);
        $optionsResolver->addAllowedTypes('Authorization', ['string']);

        return $optionsResolver;
    }

    /**
     * @return null
     *
     * @throws \Braze\Exception\PostContentBlocksCreateBadRequestException
     * @throws \Braze\Exception\PostContentBlocksCreateUnauthorizedException
     * @throws \Braze\Exception\PostContentBlocksCreateForbiddenException
     * @throws \Braze\Exception\PostContentBlocksCreateNotFoundException
     * @throws \Braze\Exception\PostContentBlocksCreateTooManyRequestsException
     * @throws \Braze\Exception\PostContentBlocksCreateInternalServerErrorException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            return json_decode($body);
        }
        if (is_null($contentType) === false && (201 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            return json_decode($body);
        }
        if (is_null($contentType) === false && (400 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateBadRequestException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
        if (is_null($contentType) === false && (401 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateUnauthorizedException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
        if (is_null($contentType) === false && (403 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateForbiddenException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
        if (is_null($contentType) === false && (404 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateNotFoundException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
        if (is_null($contentType) === false && (429 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateTooManyRequestsException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
        if (is_null($contentType) === false && (500 === $status && mb_strpos(strtolower($contentType), 'application/json') !== false)) {
            throw new \Braze\Exception\PostContentBlocksCreateInternalServerErrorException($serializer->deserialize($body, 'Braze\Model\Error', 'json'), $response);
        }
    }

    public function getAuthenticationScopes(): array
    {
        return ['BearerAuth'];
    }
}
