<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class CampaignsTriggerSendPostBodyRecipientsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var CampaignsTriggerSendPostBodyRecipientsItemUserAlias
     */
    protected $userAlias;
    /**
     * @var string
     */
    protected $externalUserId;
    /**
     * @var array<string, mixed>
     */
    protected $triggerProperties;
    /**
     * @var bool
     */
    protected $sendToExistingOnly;
    /**
     * @var CampaignsTriggerSendPostBodyRecipientsItemAttributes
     */
    protected $attributes;

    public function getUserAlias(): CampaignsTriggerSendPostBodyRecipientsItemUserAlias
    {
        return $this->userAlias;
    }

    public function setUserAlias(CampaignsTriggerSendPostBodyRecipientsItemUserAlias $userAlias): self
    {
        $this->initialized['userAlias'] = true;
        $this->userAlias = $userAlias;

        return $this;
    }

    public function getExternalUserId(): string
    {
        return $this->externalUserId;
    }

    public function setExternalUserId(string $externalUserId): self
    {
        $this->initialized['externalUserId'] = true;
        $this->externalUserId = $externalUserId;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getTriggerProperties(): iterable
    {
        return $this->triggerProperties;
    }

    /**
     * @param array<string, mixed> $triggerProperties
     */
    public function setTriggerProperties(iterable $triggerProperties): self
    {
        $this->initialized['triggerProperties'] = true;
        $this->triggerProperties = $triggerProperties;

        return $this;
    }

    public function getSendToExistingOnly(): bool
    {
        return $this->sendToExistingOnly;
    }

    public function setSendToExistingOnly(bool $sendToExistingOnly): self
    {
        $this->initialized['sendToExistingOnly'] = true;
        $this->sendToExistingOnly = $sendToExistingOnly;

        return $this;
    }

    public function getAttributes(): CampaignsTriggerSendPostBodyRecipientsItemAttributes
    {
        return $this->attributes;
    }

    public function setAttributes(CampaignsTriggerSendPostBodyRecipientsItemAttributes $attributes): self
    {
        $this->initialized['attributes'] = true;
        $this->attributes = $attributes;

        return $this;
    }
}
