<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class CampaignsTriggerSendPostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $campaignId;
    /**
     * @var string
     */
    protected $sendId;
    /**
     * @var string
     */
    protected $triggerProperties;
    /**
     * @var bool
     */
    protected $broadcast;
    /**
     * @var CampaignsTriggerSendPostBodyAudience
     */
    protected $audience;
    /**
     * @var CampaignsTriggerSendPostBodyRecipientsItem[]
     */
    protected $recipients;

    public function getCampaignId(): string
    {
        return $this->campaignId;
    }

    public function setCampaignId(string $campaignId): self
    {
        $this->initialized['campaignId'] = true;
        $this->campaignId = $campaignId;

        return $this;
    }

    public function getSendId(): string
    {
        return $this->sendId;
    }

    public function setSendId(string $sendId): self
    {
        $this->initialized['sendId'] = true;
        $this->sendId = $sendId;

        return $this;
    }

    public function getTriggerProperties(): string
    {
        return $this->triggerProperties;
    }

    public function setTriggerProperties(string $triggerProperties): self
    {
        $this->initialized['triggerProperties'] = true;
        $this->triggerProperties = $triggerProperties;

        return $this;
    }

    public function getBroadcast(): bool
    {
        return $this->broadcast;
    }

    public function setBroadcast(bool $broadcast): self
    {
        $this->initialized['broadcast'] = true;
        $this->broadcast = $broadcast;

        return $this;
    }

    public function getAudience(): CampaignsTriggerSendPostBodyAudience
    {
        return $this->audience;
    }

    public function setAudience(CampaignsTriggerSendPostBodyAudience $audience): self
    {
        $this->initialized['audience'] = true;
        $this->audience = $audience;

        return $this;
    }

    /**
     * @return CampaignsTriggerSendPostBodyRecipientsItem[]
     */
    public function getRecipients(): array
    {
        return $this->recipients;
    }

    /**
     * @param CampaignsTriggerSendPostBodyRecipientsItem[] $recipients
     */
    public function setRecipients(array $recipients): self
    {
        $this->initialized['recipients'] = true;
        $this->recipients = $recipients;

        return $this;
    }
}
