<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class CampaignsTriggerScheduleCreatePostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $campaignId;
    /**
     * @var string
     */
    protected $sendId;
    /**
     * @var list<CampaignsTriggerScheduleCreatePostBodyRecipientsItem>
     */
    protected $recipients;
    /**
     * @var CampaignsTriggerScheduleCreatePostBodyAudience
     */
    protected $audience;
    /**
     * @var bool
     */
    protected $broadcast;
    /**
     * @var array<string, mixed>
     */
    protected $triggerProperties;
    /**
     * @var CampaignsTriggerScheduleCreatePostBodySchedule
     */
    protected $schedule;

    public function getCampaignId(): string
    {
        return $this->campaignId;
    }

    public function setCampaignId(string $campaignId): self
    {
        $this->initialized['campaignId'] = true;
        $this->campaignId = $campaignId;

        return $this;
    }

    public function getSendId(): string
    {
        return $this->sendId;
    }

    public function setSendId(string $sendId): self
    {
        $this->initialized['sendId'] = true;
        $this->sendId = $sendId;

        return $this;
    }

    /**
     * @return list<CampaignsTriggerScheduleCreatePostBodyRecipientsItem>
     */
    public function getRecipients(): array
    {
        return $this->recipients;
    }

    /**
     * @param list<CampaignsTriggerScheduleCreatePostBodyRecipientsItem> $recipients
     */
    public function setRecipients(array $recipients): self
    {
        $this->initialized['recipients'] = true;
        $this->recipients = $recipients;

        return $this;
    }

    public function getAudience(): CampaignsTriggerScheduleCreatePostBodyAudience
    {
        return $this->audience;
    }

    public function setAudience(CampaignsTriggerScheduleCreatePostBodyAudience $audience): self
    {
        $this->initialized['audience'] = true;
        $this->audience = $audience;

        return $this;
    }

    public function getBroadcast(): bool
    {
        return $this->broadcast;
    }

    public function setBroadcast(bool $broadcast): self
    {
        $this->initialized['broadcast'] = true;
        $this->broadcast = $broadcast;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getTriggerProperties(): iterable
    {
        return $this->triggerProperties;
    }

    /**
     * @param array<string, mixed> $triggerProperties
     */
    public function setTriggerProperties(iterable $triggerProperties): self
    {
        $this->initialized['triggerProperties'] = true;
        $this->triggerProperties = $triggerProperties;

        return $this;
    }

    public function getSchedule(): CampaignsTriggerScheduleCreatePostBodySchedule
    {
        return $this->schedule;
    }

    public function setSchedule(CampaignsTriggerScheduleCreatePostBodySchedule $schedule): self
    {
        $this->initialized['schedule'] = true;
        $this->schedule = $schedule;

        return $this;
    }
}
