<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class CatalogsCatalogNameItemsPostBodyItemsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $city;
    /**
     * @var string
     */
    protected $cuisine;
    /**
     * @var int
     */
    protected $rating;
    /**
     * @var bool
     */
    protected $loyaltyProgram;
    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->initialized['city'] = true;
        $this->city = $city;

        return $this;
    }

    public function getCuisine(): string
    {
        return $this->cuisine;
    }

    public function setCuisine(string $cuisine): self
    {
        $this->initialized['cuisine'] = true;
        $this->cuisine = $cuisine;

        return $this;
    }

    public function getRating(): int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->initialized['rating'] = true;
        $this->rating = $rating;

        return $this;
    }

    public function getLoyaltyProgram(): bool
    {
        return $this->loyaltyProgram;
    }

    public function setLoyaltyProgram(bool $loyaltyProgram): self
    {
        $this->initialized['loyaltyProgram'] = true;
        $this->loyaltyProgram = $loyaltyProgram;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->initialized['createdAt'] = true;
        $this->createdAt = $createdAt;

        return $this;
    }
}
