<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class UsersDeletePostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string[]
     */
    protected $externalIds;
    /**
     * @var string[]
     */
    protected $brazeIds;
    /**
     * @var UsersDeletePostBodyUserAliasesItem[]
     */
    protected $userAliases;

    /**
     * @return string[]
     */
    public function getExternalIds(): array
    {
        return $this->externalIds;
    }

    /**
     * @param string[] $externalIds
     */
    public function setExternalIds(array $externalIds): self
    {
        $this->initialized['externalIds'] = true;
        $this->externalIds = $externalIds;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getBrazeIds(): array
    {
        return $this->brazeIds;
    }

    /**
     * @param string[] $brazeIds
     */
    public function setBrazeIds(array $brazeIds): self
    {
        $this->initialized['brazeIds'] = true;
        $this->brazeIds = $brazeIds;

        return $this;
    }

    /**
     * @return UsersDeletePostBodyUserAliasesItem[]
     */
    public function getUserAliases(): array
    {
        return $this->userAliases;
    }

    /**
     * @param UsersDeletePostBodyUserAliasesItem[] $userAliases
     */
    public function setUserAliases(array $userAliases): self
    {
        $this->initialized['userAliases'] = true;
        $this->userAliases = $userAliases;

        return $this;
    }
}
