<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Braze\Model;

class V2SubscriptionStatusSetPostBody extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var V2SubscriptionStatusSetPostBodySubscriptionGroupsItem[]
     */
    protected $subscriptionGroups;

    /**
     * @return V2SubscriptionStatusSetPostBodySubscriptionGroupsItem[]
     */
    public function getSubscriptionGroups(): array
    {
        return $this->subscriptionGroups;
    }

    /**
     * @param V2SubscriptionStatusSetPostBodySubscriptionGroupsItem[] $subscriptionGroups
     */
    public function setSubscriptionGroups(array $subscriptionGroups): self
    {
        $this->initialized['subscriptionGroups'] = true;
        $this->subscriptionGroups = $subscriptionGroups;

        return $this;
    }
}
