name: build
on: [push, pull_request]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build library
        run: composer build

      - name: Check Git working tree
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Detected uncommitted changes. See status below:'
            git diff
            exit 1
          fi
