name: dependabot-build
on: pull_request

permissions:
  contents: read

jobs:
  dependabot-build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build library
        run: composer build

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix .

      - name: Create diff of changes
        run: |
          git add -A
          git diff --cached --binary > /tmp/changes.patch

      - name: Upload build diff
        uses: actions/upload-artifact@v7
        with:
          name: dependabot-build-${{ github.run_id }}
          path: /tmp/changes.patch
          retention-days: 1
