name: php-cs-fixer-build
on:
  pull_request:
    paths:
      - "**.php"

permissions:
  contents: read

jobs:
  php-cs-fixer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get php-cs-fixer version
        id: php-cs-fixer
        run: |
          VERSION=$(jq -r '."require-dev"."friendsofphp/php-cs-fixer"' composer.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: php-cs-fixer:${{ steps.php-cs-fixer.outputs.version }}

      - name: Run php-cs-fixer
        run: php-cs-fixer fix .

      - name: Create diff of changes
        run: |
          git add -A
          git diff --cached --binary > /tmp/changes.patch

      - name: Upload style diff
        uses: actions/upload-artifact@v7
        with:
          name: php-cs-fixer-${{ github.run_id }}
          path: /tmp/changes.patch
          retention-days: 1
