name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          composer dumpautoload
          vendor/bin/pest --coverage --coverage-clover=coverage.xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
         files: coverage.xml
